---
title: "Practice Problem Set - Solution"
subtitle: "BUSS254 Investments"
author: "Prof. Ji-Woong Chung"
format: html
number-sections: true
execute:
    echo: false
    eval: true
---

-   If you notice any typos or errors, please feel free to [email me](chung_jiwoong@korea.ac.kr).

---

## Problem

Suppose you want to buy a 90-day treasury bill with a face value of \$10,000 and a discount (= bank discount rate) of 4\%. The price you would pay for this bill is? Use Actual/360.



**Solution:** Price = Face value - (Face value x Bank discount rate x Days to maturity / 360)

Price = 10,000 - (10,000 x 0.04 x 90 / 360)

Price = 9,900

---

## Problem

Suppose you want to sell a 180-day commercial paper with a face value of \$50,000 and a money market yield of 5\%. The price you would receive for this paper is? Use Actual/360.



**Solution:** 

Price = Face value / (1 + Money market yield x Days to maturity / 360)

Price = 50,000 / (1 + 0.05 x 180 / 360)

Price = 48,780.48

---

## Problem

Suppose you want to hedge your exposure to the British pound by using a money market hedge. You have £100,000 receivable in six months and the current spot rate is \$1.40/£. The annual interest rate in the US is 2\% and in the UK is 3\%. Follow the the steps below. Use ACT/365.



(A) Borrow an amount of pounds that will grow to £100,000 in six months at the UK interest rate. How much?

**Solution:**

Amount borrowed = £100,000 / (1 + 0.03 x 180 / 365)  
Amount borrowed = £98,493.15

(B) Convert the borrowed pounds into dollars at the spot rate.

**Solution:**

Amount converted = £98,493.15 x \$1.40/£  
Amount converted = \$137,890.41

(C) Invest the dollars in a US money market instrument that will mature in six months at the US interest rate. How much will it become?

**Solution:**

Amount invested = \$137,890.41 x (1 + 0.02 x 180 /365)  
Amount invested = \$139,250.425

(D) Use the proceeds from the receivable to repay the pound loan and keep the remaining dollars as your hedged amount. What is the implied exchange rate you apply in six months?

**Solution:** \$139,250.425/ £100,000 = \$1.3925/£

---

## Problem

Suppose you want to sell a 120-day floating-rate note with a face value of \$100,000 and a coupon rate of LIBOR + 0.5\%. The current LIBOR is 2\% and the required yield spread by investors is 0.25\% over the reference rate. The price you would receive for this FRN is?



**Solution:**

Price = (Face value + Face value \* Coupon rate) / (1 + Required yield spread \* Days to maturity / 360)

Price = (100,000 + 100,000 \* (0.02 + 0.005)) / (1 + (0.02 + 0.0025) \* 120 /360)

Price = \$102,500 / \$101,016.67

Price = \$101,477.78

---

## Problem

On 6 September 2020, Bank A (borrower) agrees to sell £1 million nominal of a UK gilt, the 8\% Treasury maturing in 2023, which is trading at a dirty price of 104.3. The agreement will begin on 7 September, the value date. The term of the trade is 30 days, so the termination date is 7 October 2020 and the agreed repo rate for the (effectively collateralised) loan is set at 6.75\%. On 7 September Bank B (lender) receives £1m nominal 8\% Treasury, which has a settlement value of £1,043,000 (clean price plus accrued interest). How much interest does Bank A pay to Bank B on the termination date, 7 October 2020? Use Actual/365.



**Solution:** 1,043,000 \* 6.75% \* 30/365 = 5786.5

---

## Problem

Between February 28, 2018, and March 1, 2018, you have a choice between owning a U.S. government bond (Actual/Actual) and a U.S. corporate bond (30/360). They pay the same coupon and have the same quoted price. Assuming no risk of default, which would you prefer? (Hint: use days360(start,end,TRUE) for 30/360 method)



**Solution:** It sounds as though you should be indifferent, but in fact you should have a marked preference for the corporate bond. Under the 30>360 day count convention used for corporate bonds, there are 3 days between February 28, 2018, and March 1, 2018. Under the actual/actual (in period) day count convention used for government bonds, there is only 1 day. You would earn approximately three times as much interest by holding the corporate bond.



---

## Programming Exercises (Optional)

Calculate the number of days between February 28, 2018, and March 1, 2018, using the following conventions and print the results:

- Actual/Actual (the actual number of days) using quantdates package.

- 30/360 day count using quantdates package.

```{r, echo=T}
if(!require('quantdates')) {
  install.packages('quantdates')
  library('quantdates')
}
if(!require('lubridate')) {
  install.packages('lubridate')
  library('lubridate')
}
library(lubridate)
library(quantdates)

start_date <- ymd("2018-02-28")
end_date <- ymd("2018-03-01")

# Actual/Actual using lubridate
actual_days <- day_count(end_date, start_date)

# 30/360 using quantdates
days_30_360 <- day_count(end_date, start_date, convention = "30/360")

# ACT/360 using quantdates
days_act_360 <- day_count(end_date, start_date, convention = "ACT/360")

print(paste("Actual/Actual number of days:", actual_days*365))
print(paste("30/360 number of days:", days_30_360*360))
print(paste("ACT/360 number of days:", days_act_360*360))
```