<!DOCTYPE html>
<html lang="en"><head>
<script src="chapter_market3_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter_market3_files/libs/quarto-html/tabby.min.js"></script>
<script src="chapter_market3_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter_market3_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="chapter_market3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter_market3_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="chapter_market3_files/libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.41">

  <meta name="author" content="Prof.&nbsp;Ji-Woong Chung">
  <title>Financial Markets: Part III</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="chapter_market3_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="chapter_market3_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="chapter_market3_files/libs/revealjs/dist/theme/quarto-8f3eebe07241f08526c91a7e9cbef8fd.css">
  <link href="chapter_market3_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="chapter_market3_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="chapter_market3_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="chapter_market3_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="chapter_market3_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="chapter_market3_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Financial Markets: Part III</h1>
  <p class="subtitle">BUSS254 Investments</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Ji-Woong Chung 
</div>
</div>
</div>

</section>
<section id="lecture-outline" class="slide level2">
<h2>Lecture Outline</h2>
<ul>
<li>Money markets: Call, Repo, CD, CP, etc.</li>
<li>Capital markets: Bond, Equity</li>
<li>Derivatives markets: Futures, options etc.</li>
<li>Trading mechanisms</li>
<li>Investment Companies</li>
<li>Reading: BKM Ch. 3 and 4</li>
</ul>
</section>
<section id="trading-mechanics" class="slide level2">
<h2>Trading Mechanics</h2>
<h3 id="why-trade">Why Trade?</h3>
<ul>
<li><strong>Information-driven trading</strong>: Traders act on private or public information.</li>
<li><strong>Non-information-driven trading</strong>:
<ul>
<li><strong>Hedging</strong>: Reducing risk exposure.</li>
<li><strong>Liquidity needs</strong>: Buying or selling for cash flow reasons.</li>
</ul></li>
<li><strong>Noise trading</strong>: Trading without fundamental justification, often irrational or random.</li>
</ul>
<h3 id="types-of-orders">Types of Orders</h3>
<ul>
<li><strong>Market order</strong>: Executes immediately at the best available price.
<ul>
<li>Quick execution vs.&nbsp;Price uncertainty.</li>
</ul></li>
<li><strong>Limit order</strong>: Specifies price and waits for execution at that price or better.
<ul>
<li>Price control vs.&nbsp;Execution uncertainty.</li>
</ul></li>
<li><strong>Stop order</strong>: Becomes a market order once the stop price is triggered.
<ul>
<li><strong>Stop-loss</strong>: Sells when the price falls below a set level.</li>
<li><strong>Stop-buy</strong>: Buys when the price rises above a set level.</li>
</ul></li>
<li><strong>Short selling</strong>: Selling borrowed shares to profit from a price decline.</li>
<li><strong>Margin trading</strong>: Borrowing funds to amplify trading positions, increasing both potential gains and risks.</li>
</ul>
</section>
<section id="margin-trading" class="slide level2">
<h2>Margin Trading</h2>
<ul>
<li><strong>Margin Purchase</strong> = Borrowing + Investor’s Equity</li>
<li><strong>Initial Margin</strong>: Minimum equity required to open a position.</li>
<li><strong>Maintenance Margin</strong>: Minimum equity required to keep the position open.</li>
<li><strong>Margin Call</strong>: If the value of securities falls too much, the investor must:
<ul>
<li>Deposit more equity (<span class="math inline">\(\ge\)</span> initial margin), or</li>
<li>Liquidate the position.</li>
</ul></li>
</ul>
</section>
<section id="margin-trading-example" class="slide level2">
<h2>Margin Trading: Example</h2>
<ul>
<li><strong>Stock Price</strong>: $100 per share</li>
<li><strong>Shares Purchased</strong>: 100</li>
<li><strong>Initial Margin</strong>: 60%</li>
<li><strong>Maintenance Margin</strong>: 30%</li>
</ul>
<p>Initial Position:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Asset</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Liability</th>
<th style="text-align: left;">Equity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stock</td>
<td style="text-align: left;">$10,000</td>
<td style="text-align: left;">Borrowed</td>
<td style="text-align: left;">$4,000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Investor Equity</td>
<td style="text-align: left;">$6,000</td>
</tr>
</tbody>
</table>
<p>If Stock Price Falls to $70:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Asset</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Liability</th>
<th style="text-align: left;">Equity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stock</td>
<td style="text-align: left;">$7,000</td>
<td style="text-align: left;">Borrowed</td>
<td style="text-align: left;">$4,000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Investor Equity</td>
<td style="text-align: left;">$3,000</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Margin%</strong> = Equity / Market Value = <span class="math inline">\(\frac{\$3,000}{\$7,000} = 43\%\)</span>
<ul>
<li>Since 43% &gt; 30% (maintenance margin), no margin call.</li>
</ul></li>
</ul>
</section>
<section id="margin-trading-maintenance-margin" class="slide level2">
<h2>Margin Trading: Maintenance Margin</h2>
<p>How far can the stock price fall before a margin call?</p>
<ul>
<li><p><strong>Maintenance Margin</strong> = 30%</p></li>
<li><p><strong>Formula for Equity</strong>: <span class="math inline">\(\text{Equity} = \text{Market Value} - \text{Borrowed Amount} = 100P - 4,000\)</span></p></li>
<li><p><strong>Margin% Formula</strong>: <span class="math inline">\(\frac{100P - 4,000}{100P} = 0.30\)</span></p></li>
<li><p><strong>Solving for Price</strong>:</p></li>
</ul>
<p><span class="math display">\[100P - 4,000 = 30P\]</span> <span class="math display">\[70P = 4,000\]</span> <span class="math display">\[P = 57.14\]</span></p>
</section>
<section id="short-sales" class="slide level2 scrollable">
<h2>Short Sales</h2>
<ul>
<li><p>Selling securities that you do not own to profit from a decline in the price of the securities</p>
<ol type="1">
<li><strong>Borrow securities</strong> through a dealer or broker.</li>
<li><strong>Sell them</strong> and deposit the proceeds along with the margin in an account.
<ul>
<li>You <strong>cannot withdraw</strong> the proceeds until you “cover” the position.</li>
</ul></li>
<li><strong>Closing out the position</strong>: Buy back the securities and return them to the lender.</li>
</ol></li>
<li><p>Naked short-selling:</p>
<ul>
<li>Selling shares <strong>without borrowing them first</strong>, assuming they can be acquired later.</li>
<li><strong>Illegal</strong> due to the risk of delivery failure.</li>
</ul></li>
</ul>
</section>
<section id="short-sales-example" class="slide level2">
<h2>Short Sales: Example</h2>
<ul>
<li><strong>Stock X</strong>: 1000 shares</li>
<li><strong>Initial Price</strong>: $100 per share</li>
<li><strong>Initial Margin</strong>: 50%</li>
<li><strong>Maintenance Margin</strong>: 30%</li>
</ul>
<p>Position Setup:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Sale Proceeds</strong></td>
<td style="text-align: left;">$100,000</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Initial Margin</strong></td>
<td style="text-align: left;">$50,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Stock Owed</strong></td>
<td style="text-align: left;">1000 shares</td>
</tr>
</tbody>
</table>
<p>Balance Sheet:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Assets</strong></th>
<th style="text-align: left;"><strong>Liabilities</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">$100,000 (sale proceeds)</td>
<td style="text-align: left;">$100,000 (shares owed)</td>
</tr>
<tr class="even">
<td style="text-align: left;">$50,000 (initial margin)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Equity</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">$50,000</td>
</tr>
</tbody>
</table>
</section>
<section id="short-sales-example-contd" class="slide level2">
<h2>Short Sales: Example (cont’d)</h2>
<ul>
<li>If Price Falls to <strong>$70 per share</strong>:</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Assets</strong></th>
<th style="text-align: left;"><strong>Liabilities</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">$100,000 (sales proceeds)</td>
<td style="text-align: left;">$70,000 (shares)</td>
</tr>
<tr class="even">
<td style="text-align: left;">$50,000 (initial margin)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Equity</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">$80,000</td>
</tr>
</tbody>
</table>
<ul>
<li>Profit Calculation:</li>
</ul>
<p><span class="math display">\[\text{Profit} = \text{Ending Equity} - \text{Beginning Equity}\]</span></p>
<p><span class="math display">\[= \$80,000 - \$50,000 = \$30,000\]</span></p>
<p><span class="math display">\[= (\text{Initial Price} - \text{New Price}) \times \text{Shares Sold Short}\]</span></p>
<p><span class="math display">\[= (100 - 70) \times 1000 = \$30,000\]</span></p>
</section>
<section id="short-sales-example-contd-1" class="slide level2">
<h2>Short Sales: Example (cont’d)</h2>
<ul>
<li>Maximum Stock Price Before Margin Call:</li>
<li><strong>Formula</strong>:</li>
</ul>
<p><span class="math display">\[\text{Margin%} = \frac{\text{Assets} - \text{Liabilities}}{\text{Market Value}}\]</span></p>
<p><span class="math display">\[= \frac{(\$150,000 - 1000P)}{1000P} = 0.30\]</span></p>
<ul>
<li><strong>Solving for P</strong>:</li>
</ul>
<p><span class="math display">\[150,000 - 1000P = 0.30 \times 1000P\]</span></p>
<p><span class="math display">\[150,000 = 1300P\]</span></p>
<p><span class="math display">\[P = 115.38\]</span></p>
<ul>
<li><span class="math inline">\(150,000\)</span>: Initial margin plus sale proceeds</li>
</ul>
</section>
<section id="trading-mechanisms" class="slide level2">
<h2>Trading Mechanisms</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Auction Market</strong></p>
<ul>
<li><strong>Centralized</strong>: Investors interact directly.</li>
<li>Orders are consolidated in a <strong>limit order book (LOB)</strong>:
<ul>
<li><strong>Bid</strong> (buy) and <strong>ask</strong> (sell) orders.</li>
</ul></li>
<li><strong>Order-driven market</strong>: Limit orders determine prices.</li>
<li><strong>Examples</strong>: NYSE, Paris, Milan, Tokyo, Korea.</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Dearler Market</strong></p>
<ul>
<li><strong>Decentralized</strong>: Trades occur via dealers.</li>
<li>Dealers quote <strong>bid-ask prices</strong>, taking on inventory risk.</li>
<li><strong>Quote-driven market</strong>: Dealers set prices.</li>
<li><strong>Examples</strong>: Nasdaq, bond markets, forex markets.</li>
</ul>
</div></div>
</section>
<section id="auction-market" class="slide level2">
<h2>Auction Market</h2>
<div style="text-align: center">
<p><img data-src="img/market_AuctionMarket.png"></p>
</div>
<ul>
<li><strong>Call (Batch) Auction</strong>: Orders are grouped and executed at specific times.
<ul>
<li>Typically at market <strong>open</strong> and <strong>close</strong>.</li>
<li>Helps <strong>reduce price distortions</strong> from temporary order imbalances.</li>
</ul></li>
<li><strong>Continuous Auction</strong>: Trading happens <strong>continuously</strong> throughout the day.</li>
</ul>
</section>
<section id="call-auction" class="slide level2">
<h2>Call Auction</h2>
<div style="text-align: center">
<p><img data-src="img//market_CallAuction.png"></p>
</div>
<p>Buy orders sorted by decreasing price (demand), and sell orders by increasing price (supply).</p>
</section>
<section id="call-auction-contd" class="slide level2">
<h2>Call Auction (cont’d)</h2>
<div style="text-align: center">
<p><img data-src="img//market_AfterCallAuction.png"></p>
</div>
<p>Price set so that supply = demand. All executable orders are filled at that price</p>
</section>
<section id="continuous-auction-limit-order-book" class="slide level2">
<h2>Continuous Auction: Limit Order Book</h2>
<ul>
<li><strong>Non-marketable orders</strong> (those not executed in the call auction) enter the <strong>Limit Order Book (LOB)</strong>.</li>
<li>Incoming orders <strong>execute against the LOB</strong> based on:
<ul>
<li><strong>Price priority</strong>: Best prices executed first.</li>
<li><strong>Time priority</strong>: Older orders executed before newer ones at the same price.</li>
</ul></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Bid</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;">Ask</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Price</td>
<td style="text-align: left;">Size</td>
<td style="text-align: left;">Time</td>
<td style="text-align: left;">Price</td>
<td style="text-align: left;">Size</td>
<td style="text-align: left;">Time</td>
</tr>
<tr class="even">
<td style="text-align: left;">74.42</td>
<td style="text-align: left;">300</td>
<td style="text-align: left;">11:49:39</td>
<td style="text-align: left;">74.48</td>
<td style="text-align: left;">300</td>
<td style="text-align: left;">11:49:35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">74.41</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">11:46:55</td>
<td style="text-align: left;">74.48</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">11:49:50</td>
</tr>
<tr class="even">
<td style="text-align: left;">74.36</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">11:48:30</td>
<td style="text-align: left;">75.74</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">08:25:17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">74.36</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">11:48:32</td>
<td style="text-align: left;">76.00</td>
<td style="text-align: left;">150</td>
<td style="text-align: left;">08:02:02</td>
</tr>
</tbody>
</table>
<ul>
<li>Market sell order of 200 (or limit sell with price <span class="math inline">\(&lt;\)</span> 74.42)</li>
<li>Market buy order of 900 (or limit buy with price <span class="math inline">\(&gt;\)</span> 75.74)</li>
<li>Because of the two orders, the bid-ask spread widens from <span class="math inline">\(74.48 - 74.42 = 0.06\)</span> to <span class="math inline">\(76.00 - 74.42 = 1.58\)</span>.
<ul>
<li><strong>The two orders have “consumed” liquidity.</strong></li>
</ul></li>
<li>Market liquidity: the ability to trade securities quickly at a price close to its consensus value</li>
</ul>
</section>
<section id="dark-pools" class="slide level2">
<h2>Dark Pools</h2>
<ul>
<li><p>Electronic trading platforms accessible only to institutional investors.</p>
<ul>
<li>Operated by stock exchanges (e.g., Turquoise by the LSE, Smartpool by Euronext, or Xetra by the Deutsche Börse), brokers (e.g., BlockCross by ICAP or Blockmatch by Instinet) or banks (e.g., SigmaX by Goldman Sachs or SG CIB AlphaY by Société Générale).</li>
<li>Operate in parallel with continuous limit order markets and offer investors an alternative way to execute their orders.</li>
</ul></li>
<li><p>Generally, dark pools do not contribute to price discovery</p>
<ul>
<li>Reference prices drawn from other markets</li>
</ul></li>
<li><p>“Dark”: orders are not displayed to the rest of market participants.</p>
<ul>
<li>Reduces the risk of information leakage</li>
</ul></li>
</ul>
</section>
<section id="dealer-market" class="slide level2">
<h2>Dealer Market</h2>
<p>In dealer markets, investors do not trade directly with each other, but must contact a dealer, find out his price, and trade at this price, or else try another dealer.</p>
<div style="text-align: center">
<p><img data-src="img//market_DealerMarket.png"></p>
</div>
</section>
<section id="dealer-market-example" class="slide level2">
<h2>Dealer Market: Example</h2>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 21%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Market Maker</strong></th>
<th style="text-align: left;"><strong>Bid Price</strong></th>
<th style="text-align: left;"><strong>Offer Price</strong></th>
<th style="text-align: left;"><strong>Quote Size</strong></th>
<th style="text-align: left;"><strong>Time</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ALPHA</td>
<td style="text-align: left;">326</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">8:53</td>
</tr>
<tr class="even">
<td style="text-align: left;">BETA</td>
<td style="text-align: left;">324</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">9:14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GAMMA</td>
<td style="text-align: left;">325</td>
<td style="text-align: left;">329</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">9:16</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA</td>
<td style="text-align: left;">323</td>
<td style="text-align: left;">332</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">8:53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPSILON</td>
<td style="text-align: left;">325</td>
<td style="text-align: left;">329</td>
<td style="text-align: left;">25 × 25</td>
<td style="text-align: left;">9:36</td>
</tr>
<tr class="even">
<td style="text-align: left;">ZETA</td>
<td style="text-align: left;">326</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">11:30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ETA</td>
<td style="text-align: left;">325</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">9:45</td>
</tr>
<tr class="even">
<td style="text-align: left;">THETA</td>
<td style="text-align: left;">325</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">9:23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IOTA</td>
<td style="text-align: left;">324</td>
<td style="text-align: left;">329</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">10:27</td>
</tr>
<tr class="even">
<td style="text-align: left;">KAPPA</td>
<td style="text-align: left;">323</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">9:45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LAMBDA</td>
<td style="text-align: left;">325</td>
<td style="text-align: left;">330</td>
<td style="text-align: left;">75 × 75</td>
<td style="text-align: left;">8:53</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Seller 4</strong> wants to sell <strong>60 shares</strong>.</li>
<li>Contacts <strong>Dealer Beta</strong>, who quotes <strong>Bid = $324, Ask = $330</strong>.</li>
<li>Seller 4 <strong>can sell at $324</strong> or try another dealer.</li>
<li><strong>Inventory Risk</strong>: Dealers face the risk of price drops after acquiring shares.</li>
</ul>
</section>
<section id="dealer-market-contd" class="slide level2">
<h2>Dealer Market (cont’d)</h2>
<h3 id="key-differences-from-limit-order-markets"><strong>Key Differences from Limit Order Markets</strong></h3>
<ul>
<li><strong>No price priority enforcement</strong> → Searching for a better price is costly.</li>
<li><strong>Dealer markets allow bargaining over price and quantity</strong>.</li>
<li>Some <strong>dealer markets display real-time quotes</strong> (e.g., Nasdaq).
<ul>
<li><strong>Corporate bond markets lack real-time data</strong>.</li>
<li><strong>Forex markets provide only indicative quotes</strong>.</li>
</ul></li>
</ul>
<h3 id="preferencing-payment-for-order-flow"><strong>Preferencing &amp; Payment for Order Flow</strong></h3>
<ul>
<li><strong>Preferencing</strong>: A broker commits to routing orders to a specific dealer.</li>
<li><strong>Payment for Order Flow</strong>: Dealers <strong>pay brokers</strong> to route trades to them.
<ul>
<li>Can impact execution quality.</li>
</ul></li>
</ul>
<h3 id="market-making-obligations"><strong>Market-Making Obligations</strong></h3>
<ul>
<li>Some markets (e.g., NYSE) require <strong>Designated Market Makers (DMMs)</strong>.</li>
<li>DMMs commit to <strong>providing liquidity</strong> by maintaining bid-ask prices up to a specific trade size.</li>
</ul>
</section>
<section>
<section id="investment-companies" class="title-slide slide level1 center">
<h1>Investment Companies</h1>

</section>
<section id="investment-companies-1" class="slide level2">
<h2>Investment Companies</h2>
<ul>
<li><p><strong>Pool funds</strong> from individual investors to invest in <strong>diversified assets</strong>.</p></li>
<li><p><strong>Types of Investment Companies</strong>:</p>
<ul>
<li><strong>Unit Investment Trusts (UITs)</strong>: Fixed portfolio, <strong>unmanaged</strong>.</li>
<li><strong>Managed Investment Companies</strong>:
<ul>
<li><strong>Open-end</strong> vs.&nbsp;<strong>Closed-end</strong> funds.</li>
<li><strong>Active</strong> vs.&nbsp;<strong>Passive</strong> management.</li>
</ul></li>
<li><strong>Other Types</strong>:
<ul>
<li><strong>Hedge Funds</strong>: Lightly regulated, private investment pools.</li>
<li><strong>Real Estate Investment Trusts (REITs)</strong>: Invest in real estate or mortgages</li>
</ul></li>
</ul></li>
<li><p>Services provided:</p>
<ul>
<li><strong>Record keeping &amp; administration</strong></li>
<li><strong>Diversification</strong>: Reducing risk exposure.</li>
<li><strong>Professional management</strong>: Fund managers handle investments.</li>
<li><strong>Lower transaction costs</strong>: Economies of scale reduce expenses.</li>
</ul></li>
</ul>
</section>
<section id="investment-companies-net-asset-value-nav" class="slide level2">
<h2>Investment Companies: Net Asset Value (NAV)</h2>
<ul>
<li>NAV: The value of each share in the investment company</li>
</ul>
<p><span class="math display">\[
\text{NAV} = \frac{\text{Market Value of Assets} - \text{Liabilities}}{\text{Shares Outstanding}}
\]</span></p>
<p><strong>Example</strong></p>
<ul>
<li>A mutual fund manages a portfolio worth <strong>$120 million</strong>, with:
<ul>
<li><strong>Liabilities</strong> = $4M (advisory fees) + $1M (rent, wages, misc.).</li>
<li><strong>Shares Outstanding</strong> = <strong>5 million</strong>.</li>
</ul></li>
</ul>
<p><span class="math display">\[
\text{NAV} = \frac{120 - 5}{5} = \$23 \text{ per share}
\]</span></p>
<p><strong>Open-End vs.&nbsp;Closed-End Funds</strong></p>
<ul>
<li><strong>Closed-end funds</strong> trade on exchanges like stocks.</li>
<li><strong>Open-end mutual funds</strong> are <strong>bought and redeemed</strong> directly from the fund at NAV, so <strong>shares outstanding change daily</strong>.</li>
</ul>
</section>
<section id="mutual-funds-how-to-invest" class="slide level2 scrollable">
<h2>Mutual Funds: How to Invest?</h2>
<ul>
<li><p><strong>Ways to Purchase Mutual Funds</strong>:</p>
<ol type="1">
<li><p><strong>Direct-marketed funds</strong>: Buy directly from the fund.</p></li>
<li><p><strong>Sales-force distributed</strong>:</p>
<ul>
<li>Sold through brokers or financial advisors.</li>
<li><strong>Revenue sharing</strong> creates potential conflicts of interest.</li>
</ul></li>
<li><p><strong>Financial supermarkets</strong>:</p>
<ul>
<li>Platforms offering multiple funds.</li>
</ul></li>
</ol></li>
<li><p><strong>Fee Structure</strong></p>
<ul>
<li><strong>Operating Expenses</strong> – Management fees</li>
<li><strong>Front-end load</strong> – <strong>Upfront commission</strong> (e.g., 4%-5%)</li>
<li><strong>Back-end load</strong> – <strong>Exit fee</strong>, decreasing over time</li>
<li><strong>12b-1 fees</strong> – Annual marketing &amp; distribution charges</li>
</ul></li>
<li><p><strong>Fees must be disclosed</strong> in the <strong>fund prospectus</strong>.</p></li>
<li><p>Different <strong>share classes</strong> offer varying fee structures.</p></li>
</ul>
</section>
<section id="example-dreyfus-high-yield-fund-2018" class="slide level2">
<h2>Example: Dreyfus High Yield Fund (2018)</h2>
<ul>
<li><strong>Front-end loads vs.&nbsp;12b-1 charges</strong>:
<ul>
<li><strong>Class A</strong>: Front-end load, lower ongoing fees.</li>
<li><strong>Class C</strong>: No front-end load, but higher annual fees.</li>
<li><strong>Class I</strong>: Institutional investors only, lowest fees.</li>
</ul></li>
</ul>
<div style="text-align: center;">
<p><img data-src="img//market_MF_Fees.png"></p>
</div>
</section>
<section id="impact-of-costs-on-investment-performance" class="slide level2">
<h2>Impact of Costs on Investment Performance</h2>
<div style="text-align: center;">
<p><img data-src="img//market_MF_Fees_Performance.png"></p>
</div>
<ul>
<li><strong>Higher costs reduce net returns</strong>.</li>
<li><strong>Lower-fee funds</strong> outperform over time due to compounding effects.</li>
</ul>
</section>
<section id="comparing-share-classes-equity-fund-example" class="slide level2 scrollable">
<h2>Comparing Share Classes: Equity Fund Example*</h2>
<p><strong>Fee Structures</strong></p>
<ul>
<li><strong>Class A</strong>: <strong>4% front-end load</strong>, no ongoing fees.</li>
<li><strong>Class B</strong>: <strong>No front-end load</strong>, but <strong>0.5% 12b-1 fees</strong> and a <strong>declining back-end load</strong>:
<ul>
<li>Starts at <strong>5%</strong>, decreases <strong>1% per year</strong> (until year 5).</li>
</ul></li>
<li><strong>Fund Portfolio Return</strong>: <strong>10% net of operating expenses</strong>.</li>
</ul>
<p><strong>Scenario: What Happens to a $10,000 Investment?</strong></p>
<ol type="1">
<li><strong>[1 year]</strong></li>
<li><strong>[4 years]</strong></li>
<li><strong>[10 years]</strong></li>
</ol>
<p><strong>Which share class provides higher net proceeds at different investment horizons?</strong></p>
</section>
<section id="investment-companies-market-size" class="slide level2">
<h2>Investment Companies: Market Size</h2>
<div style="text-align: center;">
<p><img data-src="img//market_MF_Size.png"></p>
</div>
</section>
<section class="slide level2">

<h3 id="investment-companies-by-region">Investment Companies: By Region</h3>
<div style="text-align: center;">
<p><img data-src="img//market_MF_By_Region.png"></p>
</div>
</section>
<section id="investment-companies-recent-development" class="slide level2">
<h2>Investment Companies: Recent Development</h2>
<ul>
<li><p><strong>Exchange-Traded Funds (ETFs)</strong>:</p>
<ul>
<li><p>Trade continuously like stocks.</p></li>
<li><p>Can be sold short or purchased on margin.</p></li>
<li><p>Generally lower costs than mutual funds.</p></li>
<li><p><strong>Advantages of ETFs</strong>:</p>
<ul>
<li>More flexible than index funds.</li>
<li>Lower expense ratios than actively managed mutual funds.</li>
<li>Tax efficiency due to in-kind redemptions.</li>
</ul></li>
<li><p><strong>Disadvantages of ETFs</strong>:</p>
<ul>
<li>Prices may deviate from <strong>Net Asset Value (NAV)</strong>.</li>
<li>Must be purchased through a broker, incurring trading costs.</li>
</ul></li>
</ul></li>
<li><p><strong>Actively Managed ETFs</strong></p>
<ul>
<li><p>Traditionally, ETFs were required to track <strong>specified indexes</strong>.</p></li>
<li><p>Recent expansion includes <strong>actively managed ETFs</strong> that follow different investment strategies:</p>
<ul>
<li>Value investing</li>
<li>Growth stocks</li>
<li>Dividend yield</li>
<li>Liquidity factors</li>
<li>Recent performance trends</li>
<li>Volatility</li>
</ul></li>
<li><p><strong>Key Feature</strong>:</p>
<ul>
<li>Unlike traditional mutual funds, actively managed ETFs <strong>disclose their portfolio composition daily</strong>.</li>
</ul></li>
</ul></li>
<li><p><strong>Non-Transparent Actively Managed ETFs</strong></p>
<ul>
<li><strong>Challenge</strong>: Frequent portfolio disclosure could allow competitors to exploit fund trading strategies.</li>
<li><strong>Solution</strong>: Development of <strong>non-transparent actively managed ETFs</strong>.</li>
<li><strong>Regulatory Approval</strong>:
<ul>
<li>In 2014, the SEC granted permission to Eaton Vance to introduce an actively managed <strong>non-transparent ETF</strong>.</li>
<li><strong>NextShares</strong> began trading in 2016.</li>
</ul></li>
<li><strong>Key Difference</strong>:
<ul>
<li>Unlike traditional ETFs, these funds limit portfolio disclosure to protect trading strategies.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="investment-companies-etf-trends" class="slide level2">
<h2>Investment Companies: ETF Trends</h2>
<div style="text-align: center;">
<p><img data-src="img//market_ETF_Size.png"></p>
<p>Source: Statistica - Global exchange-traded funds (ETFs) from 2003 to 2021</p>
</div>
</section>
<section id="investment-companies-mutual-fund-performance" class="slide level2">
<h2>Investment Companies: Mutual Fund Performance</h2>
<div style="text-align: center;">
<p><img data-src="img//market_MF_Performance.png"></p>
</div>
</section>
<section id="investment-companies-performance-persistence" class="slide level2">
<h2>Investment Companies: Performance Persistence</h2>
<div style="text-align: center;">
<p><img data-src="img//market_MF_Persistence.png"></p>
</div>
</section>
<section id="investment-companies-closed-end-funds" class="slide level2">
<h2>Investment Companies: Closed-end Funds</h2>
<div style="text-align: center;">
<p><img data-src="img//market_Closed_End.png"></p>
</div>
<ul>
<li><p>Closed-end Fund Puzzle</p>
<ul>
<li>The common divergence of price from net asset value, often by wide margins, is a puzzle that has yet to be fully explained</li>
</ul></li>
</ul>
</section>
<section id="investment-companies-hedge-funds" class="slide level2">
<h2>Investment Companies: Hedge Funds</h2>
<ul>
<li><strong>Hedge Funds</strong>:
<ul>
<li>Typically structured as <strong>private partnerships</strong>.</li>
<li>Subject to <strong>minimal regulation</strong>, unlike mutual funds.</li>
<li>Can pursue <strong>complex investment strategies</strong>:
<ul>
<li>Heavy use of <strong>derivatives</strong>.</li>
<li><strong>Short selling</strong>.</li>
<li><strong>Leverage</strong> to amplify returns.</li>
</ul></li>
<li>Not available to the general public; open only to <strong>wealthy or institutional investors</strong>.</li>
</ul></li>
<li><strong>Lock-Up Periods</strong>:
<ul>
<li>Many hedge funds require an initial <strong>“lock-up” period</strong> of several years.</li>
<li>Investors cannot withdraw funds during this time.</li>
<li>Allows hedge funds to invest in <strong>illiquid assets</strong> without facing immediate redemption pressure.</li>
</ul></li>
</ul>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<ul>
<li><a href="https://www.bok.or.kr/portal/bbs/P0000603/list.do?menuNo=200460">Financial Markets in Korea (Bank of Korea)</a></li>
<li><a href="https://ktb.moef.go.kr/eng/main.do">Korea Treasury Bonds (Ministry of Economy and Finance)</a></li>
<li><a href="https://www.sifma.org/resources/research/fact-book/">Capital Market Factbook (SIFMA)</a></li>
<li><a href="http://global.krx.co.kr/">The Korea Exchange (KRX)</a></li>
<li><a href="https://www.icifactbook.org/">Investment Company Factbook (ICI)</a></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="chapter_market3_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="chapter_market3_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/reveal-text-resizer/revealjs-text-resizer.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="chapter_market3_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="chapter_market3_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealTextResizer, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>